Create template react app
kontent-ai/custom-element-template-react pull request #1
Opened 2022-10-27 14:34 UTC by JiriLojda

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2022-11-01 09:02 UTC, IvanKiral requested changes

2022-11-01 09:02 UTC, IvanKiral commented on README.md
>  [contributors-shield]: https://img.shields.io/github/contributors/Kentico/kontent-custom-element-samples.svg?style=for-the-badge
There are wrong links for badges

+ nitpick: markdown lint is showing me some warnings like trailing whitespaces :D

2022-11-01 15:02 UTC, JiriLojda commented on README.md
>  [contributors-shield]: https://img.shields.io/github/contributors/Kentico/kontent-custom-element-samples.svg?style=for-the-badge
I updated the links but I can't see any markdown lint suggestions in my IDE.

2022-11-03 10:10 UTC, IvanKiral commented
Internally we agreed to rework the config to contain some property to show the use case

2022-11-03 10:10 UTC, IvanKiral requested changes

2022-11-03 10:10 UTC, IvanKiral commented on README.md
>  [discussion-shield]: https://img.shields.io/discord/821885171984891914?color=%237289DA&label=Kontent%20Discord&logo=discord&style=for-the-badge
Would it be possible to have kontent.ai badge?

2022-11-21 10:34 UTC, strizr approved these changes

2022-11-21 10:51 UTC, IvanKiral approved these changes

2022-11-21 10:53 UTC, merged