Rewrite the template to starter
kontent-ai/custom-element-template-react pull request #6
Opened 2024-03-01 10:06 UTC by JiriLojda

- Prepare a couple of useful functions and hooks
- Create a context component that will initialize the custom element, put useful info into React context and handle the height of the element
- Adjust the readme to guide through the process of starting a custom element from this starter

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2024-03-04 11:06 UTC, IvanKiral requested changes

2024-03-04 11:06 UTC, IvanKiral commented on README.md
> -This template can be used to jumpstart your own custom element development with Kontent.ai. It contains all the necessary tools for creating a new [Custom Element](https://kontent.ai/learn/tutorials/
nitpick: link to Kontent.ai :D

2024-03-04 11:06 UTC, IvanKiral commented on README.md
> +## Running the project
NITPICK: My personal preference would be having this more to the top.. Less skilled developers who are not working so much with `package.json` might find this information useful more times when developing. Ultimately, the decision is on you

2024-03-04 11:06 UTC, IvanKiral commented on src/IntegrationApp.tsx
> +        selectAssets,
Why not add atleast one button with selectAssets? :) it showcases how to use it and might help to some newbies developers :)

2024-03-04 12:07 UTC, JiriLojda commented on src/IntegrationApp.tsx
> +        selectAssets,
I wanted the app to be as clean as possible, but a small example might be worth it. I will try to add something.

2024-03-04 12:39 UTC, JiriLojda commented on README.md
> +## Running the project
What do you mean by "this"? The "Utilities in this repository" section?

2024-03-04 12:41 UTC, JiriLojda commented on README.md
> -This template can be used to jumpstart your own custom element development with Kontent.ai. It contains all the necessary tools for creating a new [Custom Element](https://kontent.ai/learn/tutorials/
No sure what you mean 😅

2024-03-05 12:02 UTC, IvanKiral commented on README.md
> +## Running the project
I meant runing the project

2024-03-05 12:02 UTC, IvanKiral commented on README.md
> -This template can be used to jumpstart your own custom element development with Kontent.ai. It contains all the necessary tools for creating a new [Custom Element](https://kontent.ai/learn/tutorials/
i am sorry i have forgotten to remove this comment

2024-03-06 12:28 UTC, IvanKiral approved these changes

2024-03-06 12:30 UTC, merged